### ISSUE TITLE
Few improvements

### ISSUE THREAD

**Issue by Groar90** [zmilla93/SlimTrade#1]
Hello,
Tried your trade helper today and I must say that I like it so far. 
To make it even better you should add:
1. Grid search support for Map stash tab (like in Trade Companion):
https://raw.githubusercontent.com/lemasato/POE-Trades-Companion/master/screenshots/ItemGrid%20Maps.png
2. Custom actions to custom buttons ;p (Like I can add custom reply "Sold" but I can't make it close the trade window at the same time)
3. Make it possible to hide that small "menu button". I can access menu from the tray If i need to and that button stays even if I close PoE so I have to close SlimTrade every time as well.

**Comment by zmilla93** [comment]
1. My work around for non standard tabs like maps is that you can left click the stash helper to search item names in the stash tab, which lets you use the in game highlighting. I do think I need to make that more clear to the users, as currently it is only stated once in the tutoria.
2. Solid idea, will likely add in the future.
3. Clicking anything that isn't POE or SlimTrade cause all SlimTrade overlays to be hidden, including the menubar. Is that not the case? Still a decent idea if people don't like clutter on their screen.

Thanks for the feedback!

**Comment by Groar90** [comment]
Ye I realised that you can click to use in game search but in case of maps the grid in Trade Companion shows which map the buyer wants specifically while search option shows every single map with that name. 
Sometimes you put map in the trade and the guy cancels the trade coz he wanted the one with 5 quality or unidentified rare :S

**Comment by zmilla93** [comment]
That fuzzy map searching is intentional. I had the opposite issue of people messaging me for a map with a prefix that was sold out, so the search wouldn't pick up similar maps that I could offer instead. I could add a toggle in the options, or even bind one option to middle mouse.

I'll look into seeing what it would take to add map tab support to the item highlighter, but as a lower priority. I honestly think using searching item name + in game highlighting is a better system overall, so I'll work on the kinks in that first.

If you have issues with the SlimTrade overlays not being hidden when you click outside of POE, feel free to open up an issue report for just that. It would certainly be a bug, but not one I can reproduce.
