### ISSUE TITLE
Broken close on kick since 0.2.5

### ISSUE THREAD

**Issue by caseg1** [zmilla93/SlimTrade#21]
Close on kick appears to have stopped working since 0.2.5 and still doesn't work in 0.2.6. It was working for me with 0.2.4.

I'm also running Poe overlay 0.6.17 and YoloMouse.

**Comment by zmilla93** [comment]
Whoops! I actually meant to remove that feature from the basics panel. The new macro system has a checkbox to set any button to be act as a close button. This change lets you set it to things like "/hideout" or "sold" instead of just "/kick".

While I may not worry about hot fixing this immediately, the next update will have this cleaned up. I'll also make the default incoming kick and outgoing hideout buttons set to close as an example, although the defaults are only creating the first time you run 0.2.5+.

**Comment by zmilla93** [comment]
It will save people a lot of confusion to just fix this now. Just released v0.2.7 which removes the close on kick button from the basics panel, and will actually set the incoming kick and outgoing hideout buttons to act as close buttons. The second part of this change will only apply to people who haven't run the program in v0.2.5+.
