### ISSUE TITLE
POE Client Path

### ISSUE THREAD

**Issue by herrfresch** [zmilla93/SlimTrade#22]
Cant change the POE Client Path! If i klick on one folder, the window closes

**Comment by zmilla93** [comment]
What version of SlimTrade are you using? Also, is this happening in the options menu, or during setup when you set the client file for the first time?

The folder select window is supposed to disappear if you click outside of POE or SlimTrade, but should reappear when tabbing back in. There is a graphical bug when doing this that could make the open window appear all white, but is fixed by closing and reopening the folder select window. 

The issue of the folder select window permanently disappearing has existed in old versions, but it doesn't occur for me in the latest version.

**Comment by herrfresch** [comment]
hi,
i use 0.2.7
when i open the SlimTrade.jar and then want to change the path under settings, the window comes up, but as soon as i want to click on a folder, slim trade disappears and the window turns white and stays white.

**Comment by zmilla93** [comment]
Sounds like it is the graphics bug I described, but it is occurring all the time for you rather than just when tabbing out. [I assume this is what it looks like?](https://i.imgur.com/ubrhGLZ.png)

Thank for the report, I'll look for a fix for this.

In the mean time, if you want to keep using the program you can manually edit the settings file to update the client.txt, just be careful to change the right thing and not accidentally delete an extra quote or comma.

- Here is the wiki page for how to find SlimTrade's settings.json file. 
- [Search for the phrase "clientPath"](https://i.imgur.com/aCS4bvj.png), the entire section you are editing is `"clientPath":"C:/Program Files (x86)/Steam/steamapps/common/Path of Exile/logs/Client.txt"`
- Change this statement to point to your client.txt file, save, and relaunch SlimTrade

The worst case scenario of doing this incorrectly is corrupting the save file, which just means SlimTrade will delete and remake it on launch. Inconvenient, but it won't actually break anything.

**Comment by zmilla93** [comment]
I realize why this might be happening. When you click the edit button, what is the title of the folder select window [shown here](https://imgur.com/a/5kseB3r)?

If it isn't "Open", SlimTrade will think you are tabbing of the game and hide the overlay, which may not work on non Windows computers, or if you are not using English as your system language. Let me know if this is the issue and I'll start testing out a fix.

**Comment by herrfresch** [comment]
Hello,
the title is open, but as soon as i click on something, the window turns white, yes the system language is german

**Comment by zmilla93** [comment]
I assume it is the German word for "Open" and not English? The check I use currently looks for the exact phrase "Open", so I'd have to manually add the equivalent phrase for all languages. I'd much rather look for a solution that will work regardless of language.

Did manually editing the client path work for you? It should allow you to use the program until I can come up with a proper solution. Thanks for the report, sorry for the inconvenience!

**Comment by zmilla93** [comment]
Fixed in v0.2.9.
