### ISSUE TITLE
German language  Support 

### ISSUE THREAD

**Issue by qLuxi** [zmilla93/SlimTrade#24]
If I play in german language with german Chat the pop up won’t work even the history doesn’t show anything. 
If I switch game und chat to English the pop up shows. 

Is there any keywords in the code for trade request that I can easy translate in German so the tool works with German chat?

**Comment by zmilla93** [comment]
Turns out that switching the game's language setting switches the @To and @From part of whispers to said language (IE @An and @Von in German), which isn't something I was aware of.

This should be a relatively easy fix, but since SlimTrade currently supports trade messages in 8 languages I'll take the time to fix this for all languages rather than just hot fixing for German.

Thanks for the report! Except this change in the next version, and sorry for the inconvenience in the mean time.

**Comment by Xorjo** [comment]
Hi zmilla93,
I had the same issue with the language. I managed to fix it for me at the moment unitl you release a new version, by changing hardcoded the to and from in `ChatParser#getMessageType` and in the `References#REGEX_CLIENT_PREFIX`. Of course this is not a fix to support multi languages.
Additionally I had to change the pattern in LangRegex for German. In my messages in the Client.txt I have no apostrophe around the `(?<league>.+)` and no points after `(?<stashX>\d+)` and `(?<stashY>\d+)` and no point at end after `von oben\\)`.

**Comment by zmilla93** [comment]
Sorry about the delay, and thanks for the additional info. I just published a prerelease of the next version with the language changes only. It would be awesome if you could verify this is working correctly before I release the full version since I don't have an easy way to test.

[Prerelease Download](https://github.com/zmilla93/SlimTrade/releases/tag/PRE-v0.2.9)

If either of you want to help me out long term and you receive trade messages in German (based on preferred language on pathofexile.com), it would be awesome if you could tell me your account name (displayed on website, not a character name). This will then let me use the trade website to generate trade messages in German so I can do proper testing myself.

**Comment by Xorjo** [comment]
I have made some trades right now. Incoming and outgoing seams to work well with the new prerelease version. The history was loaded and updated correctly as far as I saw.

My prefered language in pathofexile.com is set to German and my account in poe is the name as it is here 'Xorjo'. You can use it to generate messages for testing.

**Comment by zmilla93** [comment]
Fixed in v0.2.9.
