### ISSUE TITLE
Stash helper suggestions

### ISSUE THREAD

**Issue by dennistlt** [zmilla93/SlimTrade#26]
**What feature would you like added?**
1) For incoming trades, currently there is a feature of searching the trade item in stash by left clicking the stash helper.  Suggest to add an input of "enter" at the end of this function.
2) Also for stash searching, suggest to search the unique items' names without the item base.  For example, instead of "Blood of the Karui Sanctified Life Flask", search "Blood of the Karui" instead.  

**Why do you want this feature added?**
1) If the Trade function is used immediately after using this stash searching function, the first input of "Enter" would be sent to the stash's search box instead of the chat box which causes the trade command to fail.
2) Right now POE's unique item tab does not let you search the full name of the unique items.

**Comment by zmilla93** [comment]
Great point of the first one. Didn't realize enter would unfocus the search box, so that will be a very nice change.

I'll have to think about the second one. I'd likely have to make a list of all the item bases used by uniques, then add a check to remove the base text only when it is a unique (IE not interfering with someone just trying to sell a "Superior Sanctified Life Flask of Heat"). Obviously it is doable, but a bit of a pain as it will potentially need updating each league, adds a huge check every time you search an item, and only affects people using the unique tab to sell. Would probably make it an opt in feature if I do add it.

**Comment by dennistlt** [comment]
Tbh the second point is an inconsistency of the game so it is probably better to suggest to GGG first.  Also if you are to implement it, there will be loads of works every new league to add the new uniques.  

Thanks for the great tool btw.

**Comment by zmilla93** [comment]
I agree that this would be much better addressed on GGG's side of things. I've added this to my list of suggestions, which I'll post on the forums at some point before the next league. Hopefully they will fix the issue, as it isn't something I wish to try addressing myself.

The first suggestion has been added in v0.2.9.
