### ISSUE TITLE
Pop-Up doesn't appear

### ISSUE THREAD

**Issue by TaYula** [zmilla93/SlimTrade#39]
When i get trade requests i dont get the pop-up, same with trade messages I send. I tried like everthing - switching render, swap to "windowed" and back to "windows fullscreen" etc. After i close PoE all the Pop-Ups that should have been there are popping onto my screen.

I asked a mate who uses SlimTrade and we matched all settings but still no different result.

**Comment by zmilla93** [comment]
Someone else who had this issue was able to fix it by running SlimTrade as administrator. This is annoying to do with a java program, but a somewhat simple way is to run command prompt as admin, then run SlimTrade from the command line.

[How to run a program from command line.](https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt)
**Note: At step 3, right click and select "Run as administrator".**

If you can test this and confirm it is a fix, let me know and I can look into an easy way to do this from within SlimTrade itself. The previous person made their own .bat file to run as admin, so I never bothered addressing it.

**Comment by TaYula** [comment]
Sadly it wasnt that easy to fix it. SlimTrade finds all the old trades in the history but it takes quite some time for it to register the new ones (like 20 min until they show up).

Ty for the first answer

**Comment by defekT1312** [comment]
I have the Problem that when i switch to second Monitor  and then back SlimTrade doesnt register an incoming Trade. Clicking Top Left Options then Save sometimes fixes this.

**Comment by Krzysiu** [comment]
I'm using POE as windowed fullscreen + Awakened POE Trade + SlimTrade and ST seems to disappear - no sound, no popups. It appears again when I minimize POE and get to ST settings. Then I can close it and it appears again.

Running as admin doesn't help. It seems to be an issue with ontop attribute, but I know WAPI is crazy with that and you need more info. So, if there's more debug you could think of, I'm ready - this tool is just too unique and great to look for other <3

**Comment by Krzysiu** [comment]
Additional info I just noticed. Sometimes the overlay menu disappears. I don't know when, but to get it back, I can hide POE window (win+d), right click on tray, settings. The moment I click on "Save" button, past request sounds start playing one by one, I see my past offers... And then when I click on POE window, it again hides and gets quiet.

**Comment by zmilla93** [comment]
SlimTrade has had significant updates since this post was made. If anyone continues to use the app and has any issues, feel free to open a new issue thread and I'll take a look.
