### ISSUE TITLE
SlimTrade whisper pup-up doesn't appear!

### ISSUE THREAD

**Issue by Exanaros** [zmilla93/SlimTrade#57]
Hi,

I just installed Slimtrade with last version of JAVA it runs ok except when i whisper to someone or vice versa the pup-up doesn't appear i have tried almost everything:

- Re-install it
- And can't run it as admin cuz its .jar
- I have win11
- My pc equipment is high performance
-  I also installed all the packages from win like runtime/ DirectX/ Framework/ java 2023
- Also tried to do what in "https://github.com/zmilla93/SlimTrade/issues/39" but doesn't fix it

I can't find solution is this app still work or doesn't have support anymore? cuz i saw some ppl using it and work fine with them.

Any advice thx in advance

**Comment by Exanaros** [comment]
Well after check the forum, i see the developer who make this app he doesn't support it anymore and i thing this app didn't get update since 2021 so time to find another app, i like this app but yah i hope the guy who made this app is ok

**Comment by zmilla93** [comment]
Sorry for the delay, and thank you for the well wishes! I had taken an extended break from this project, but just put out a major update.

Try following the steps in the [troubleshooting guide](https://github.com/zmilla93/SlimTrade/wiki/Troubleshooting). This problem is usually caused by an incorrect path to the client.txt file.
