### ISSUE TITLE
SlimTrade only starts with PowerShell

### ISSUE THREAD

**Issue by KalleWalle** [zmilla93/SlimTrade#61]
Hi I'm new to github and SlimTrade.
So my problem is SlimTrade only starts with the javaw -jar "slimtrade.jar" command.
For the .jar Java Platform SE binary is selected for open with but after double click nothing is happening.
After starting it with the PowerShell command everything is working fine so maybe it's not a bug instead a user or settings error.
I'm on win10 64bit and using java 64bit everything is updated.
I hope someone can help me with the problem and sorry for the bad endlich 😅

**Comment by fubaWoW** [comment]
This is definitely not a bug of the App then, because with the "correct path" it is also working on your machine, obviously!  

Check your Registry for the correct Java path for JAR files here:
``HKEY_CLASSES_ROOT\jarfile\shell\open\command``

this should look like this:
``"C:\Program Files\Java\jdk-17\bin\javaw.exe" -jar "%1" %*``

if this path is also correct and it still does not work with "Double Click" to run, you maybe? have broken something in your OS, maybe completely Uninstall and Re-Install Java then?

**Comment by serbalin** [comment]
Not initiating at all after the update and my old version is updating all the time is not starting anymore please help

**Comment by zmilla93** [comment]
Sorry for the delay! Detailed instructions to run the program can be found in the [troubleshooting guide](https://github.com/zmilla93/SlimTrade/wiki/Troubleshooting). Make sure to check "Always use this app to open .jar files". If that doesn't work, you can try using SlimTrade.bat to run the program as administrator instead.
