### ISSUE TITLE
pls add right click -> close all

### ISSUE THREAD

**Issue by Esionru** [zmilla93/SlimTrade#65]
**What feature would you like added?**
pls add right click -> close all

**Comment by Esionru** [comment]
or button

**Comment by zmilla93** [comment]
This functionality already exists for the most part.

Right clicking the close button for incoming trades will close all messages that have the same item name. For outgoing trades, it closes all except for the message clicked, so you can use it to select the correct message. Does this cover what you are asking about?

This is explained on the incoming/outgoing macro windows in the options window. I should probably add a line about it to the tutorial since I know a lot of people miss this feature.

**Comment by Esionru** [comment]
oh thank you very much

**Comment by Esionru** [comment]
Is it possible to make the tray icon colored? Sometimes I feel like there's dirt on my screen :D

**Comment by zmilla93** [comment]
Yeah, the current icon is very hard to see on dark themes. It will be changed to a chaos orb in the next patch. I meant to have in changed already, but had to fix some scaling issues first.

**Comment by scottmudge** [comment]
Thanks for the updates @zmilla93 , I thought this project might have been dead before this latest update. Love the changes!

One feature I had on a fork (poorly implemented) of the previous version was to be able to change the base green/red color of incoming/outgoing trade boxes, with the lighter/darker variants of those colors (used for click/hover highlights if I remember) were derived from their customized base color.

This would be awesome with the update too, if you have the time.

**Comment by zmilla93** [comment]
Glad you are liking the update!

Inverting the colors is easy enough, would just need to make sure the text color is still readable. I know the trade message colors don't look the best with some of the new themes, so I might add in an option for more color variants. Will have to think about a solution that works well for all themes.

**Comment by zmilla93** [comment]
First two issues are resolved in v0.4.1. Improvements to trade message colors will come in a future update.
