### ISSUE TITLE
64 bit issue

### ISSUE THREAD

**Issue by hovercenteral** [zmilla93/SlimTrade#8]
Hello first of all idk if this is a bug but my macro buttons doesn't work with 64 bit client. Is there a way to fix this?

**Comment by zmilla93** [comment]
I need more information to work with.

Do you mean the 64 bit POE client? This shouldn't be the cause of any issues since SlimTrade doesn't interface with the game directly.
Is this all macro buttons, or just some of them. Have they always not worked, or is it sometimes? Please also include operating system.

As an aside, make sure your actual Java installation is up to date.

**Comment by hovercenteral** [comment]
My Java is up do date and it is 64 bit. Not a single macro works when i open the game with "PathOfExile_x64.exe" but program captures any whisper etc. I tried deleting client.txt, tried reinstalling java and trien reinstalling slimtrade.jar but none seems to work for me.

**Comment by zmilla93** [comment]
What is your operating system?

**Comment by hovercenteral** [comment]
I am using win10 and I figured it. For some reason i checked the box saying disable display scaling..  in the compatibility settings and that was the problem >_<

**Comment by zmilla93** [comment]
Glad you were able to resolve it!
